---
- name: Install ntlmaps
  apt:
    name: ntlmaps
    update_cache: "{{ apt_update_cache|default(yes) }}"
    cache_valid_time: "{{ apt_cache_valid_time|default(3600) }}"
  tags: ntlmaps

- name: Configure ntlmaps
  template:
    src: templates/server.cfg.j2
    dest: /etc/ntlmaps/server.cfg
    owner: root
    group: root
    mode: 0600
  become: yes
  notify: restart ntlmaps
  tags: ntlmaps